/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/3D/Column2_61Stages/Column2_61Stages.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelColumn2() {
  const { nodes, materials } = useGLTF('./3D/Column2_61Stages/Column2_61Stages.gltf')
    console.log(nodes, materials)
  return (
      <></>
    // <group dispose={null} scale={0.2}>
    //   <mesh
    //     geometry={nodes['02_Shell_1'].geometry}
    //     material={materials.Simacro_Shells}
    //     position={[0, 24.08, 0]}
    //     rotation={[-Math.PI / 2, 0, 0]}
    //     scale={0.752} />
    //   <mesh
    //     geometry={nodes['02_Parts_1'].geometry}
    //     material={materials.Simacro_Parts}
    //     position={[0, 27.781, 0]}
    //     rotation={[-Math.PI / 2, 0, 0]}
    //     scale={[0.752, 0.752, 0.612]} />
    // </group>
  )
}

// useGLTF.preload('./3D/Column2_61Stages/Column2_61Stages.gltf')
