/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/3D/Labels/Labels.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Labels.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Label_05_1.geometry} material={materials.DefaultMaterial} position={[34.114, 24, -2.476]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Label_02_1.geometry} material={materials.DefaultMaterial} position={[23.1, 57, -0.352]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Label_01_2_1.geometry} material={materials.DefaultMaterial} position={[7.154, 73, -0.352]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Label_01_1_1.geometry} material={materials.DefaultMaterial} position={[-5.652, 50, -0.352]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Label_03_1.geometry} material={materials.DefaultMaterial} position={[-29.41, 39, -36.196]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Label_04_1.geometry} material={materials.DefaultMaterial} position={[-29.367, 20.5, -42.985]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Label_06_1.geometry} material={materials.DefaultMaterial} position={[-73.145, 39, -38.217]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Label_07_1.geometry} material={materials.DefaultMaterial} position={[-115.654, 40, -35.707]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/Labels.gltf')
